### PR TITLE
Changes on `setURL`(code and Docs) | added `gray` as equal as `grey`

### PR DESCRIPTION
**Pull request by EhsanFox**
i didn't find anything about the docs to change tho, but I guess that would be it

### CODE REVIEW

**Comment by Galaxy-Coding** [comment]
Thank you for accepting my suggestion

**Comment by EhsanFox** [comment]
the funny thing is, i had this problem too with the 'grey' color XD

**Comment by EhsanFox** [comment]
Both `grey` and `gray` will work.

**Comment by EhsanFox** [comment]
Title Changed

**Comment by EhsanFox** [comment]
Automaticly setStyle ot `url` whenever you use `setURL` function!

**Comment by EhsanFox** [comment]
Everything should be fine.

**Comment by AngeloCore** [comment]
I will merge this pr, only if you remove the auto style changing

**Comment by EhsanFox** [comment]
ok, gonna fix it rn

**Comment by EhsanFox** [comment]
Fixed

**Comment by AngeloCore** [comment]
Gimme your discord tag

**Comment by EhsanFox** [comment]
BoyCode : )

**Comment by EhsanFox** [comment]
^BoyCode#8212

**Pull request merged**
