### PR TITLE
reformatting README.md

### PR DESCRIPTION
**Pull request by es183923**

### CODE REVIEW

**Comment by EhsanFox** [comment]
these changes are unnecessary, everything is covered in PR #13

**Comment by AngeloCore** [comment]
Remove the image, because we cant use the image in npm...

**Comment by es183923** [comment]
You can just use the raw github link for the image. It's usually best to use the github link instead of pays.host.

**Comment by es183923** [comment]
Oh, you will have to change the URL from `https://raw.githubusercontent.com/es183923/discord-buttons/main/example_image.png` to `https://raw.githubusercontent.com/AngeloCore/discord-buttons/main/example_image.png`

**Comment by EhsanFox** [comment]
The next update is coming and i covered everything including new Readme and Docs.
Thanks for your help, but with respect, I don't think this PR's gonna be merged.

**Comment by es183923** [comment]
Okay, that's fine. I'm closing this PR.

**Pull request closed without merging**
