### PR TITLE
importing ButtonCollector

### PR DESCRIPTION
**Pull request by Assassin-1234**
this should fix button collectors not working properly

### CODE REVIEW

**Comment by xHyroM** [comment]
endReason is already being addressed. https://github.com/AngeloCore/discord-buttons/pull/39

**Comment by Assassin-1234** [comment]
> endReason is already being addressed. #39

There isn't a change in the buttonCollector class, I just did that to make the code even without conflicts

**Comment by Assassin-1234** [comment]
up to date now

**Comment by xHyroM** [comment]
Angelo told me he would fix it and that I should close the RP. If you remove the get then djs12 will work but djs13 won't. Angelo wants djs13 to go too, so he said he'll fix it himself.

**Comment by Assassin-1234** [comment]
I don't think djs v13 will be coming out anytime soon and collectors still don't work, but if he's already working on it then I'll do ahead and close this pr, thanks for your time :)

**Comment by Assassin-1234** [comment]
Screenshot_20210531-001041
Forgot about this lol

**Pull request closed without merging**
