### PR TITLE
fix: (typings)

### PR DESCRIPTION
**Pull request by Tolfx**
Seems like it already has an default value in the src code, which makes it pointless to force in data if there is a default value of `{}`

### CODE REVIEW

**Comment by AngeloCore** [comment]
We now have a lot typings errors...

**Comment by Tolfx** [comment]
> We now have a lot typings errors...

I see.. well If I got time I could try the dev and see what kind of options would resolve the issues when I got time.

**Comment by AngeloCore** [comment]
Ok, thanks
Also check #83

**Comment by Tolfx** [comment]
Made it a little smarter, but can't seem to figure out .send() function, and how to make it work with `message.channel.send("hello", button);` without giving a warning, will check on it later.
image

**Comment by Tolfx** [comment]
Fixed this issue, so won't complain anymore..
image

**Pull request merged**
