### PR TITLE
Some cool changes for emoji support on MessageButton.

### PR DESCRIPTION
**Pull request by TheArmagan**
### Emoji Stuff
- Now supports animated emojis too.
- Optimized regex usage in Utils by making it global.
- Type script support added for setEmoji method.
- Emoji parsing optimized.
- Automatically generates custom_id for ease of use.

### Other
- .gitignore file added for ease of use.

### CODE REVIEW

**Comment by EhsanFox** [comment]
All this stuff is covered in the next update, please close your PR!

**Comment by AngeloCore** [comment]
remove **test2.js** and discord.js from the dependencies

**Comment by TheArmagan** [comment]
> remove **test2.js** and discord.js from the dependencies

sure

**Comment by AngeloCore** [comment]
Ok, whats your discord tag?

**Comment by AngeloCore** [comment]
Also we dont need this commit
https://github.com/AngeloCore/discord-buttons/pull/40/commits/15dd515d74d76e0df0ac6c0cf01505539daa1db9

**Comment by AngeloCore** [comment]
You can save only this
image

**Comment by TheArmagan** [comment]
My discord tag: Armagan#4869

**Comment by TheArmagan** [comment]
> Also we dont need this [15dd515](https://github.com/AngeloCore/discord-buttons/commit/15dd515d74d76e0df0ac6c0cf01505539daa1db9) commit

what do you mean

**Comment by AngeloCore** [comment]
Make new pr for the new version!

**Pull request closed without merging**
