### PR TITLE
Typescript changes

### PR DESCRIPTION
**Pull request by DevScyu**
Adds better typescript support

### CODE REVIEW

**Comment by alhassanv** [comment]
Hey @DevScyu,
I have tested this and I have a few notes.
- This works on v12 but doesn't work on v13.
- To get it working on typescript you have to get a bit hacky and do `(message.channel as ExtendedTextChannel)`.
Other than that it seemed to work nice.

**Comment by DevScyu** [comment]
> * This works on v12 but doesn't work on v13.

I'll take a look at this

> * To get it working on typescript you have to get a bit hacky and do `(message.channel as ExtendedTextChannel)`.

Yes, you have to cast the channel to the custom ExtendedTextChannel to allow the buttons and components to be sent via the .send method

**Comment by alhassanv** [comment]
> > * This works on v12 but doesn't work on v13.
> I'll take a look at this

You can remove v13 support since it has been merged into discord.js master branch.

**Comment by AngeloCore** [comment]
> You can remove v13 support since it has been merged into discord.js master branch.

no, their code is buggy

**Comment by alhassanv** [comment]
> > You can remove v13 support since it has been merged into discord.js master branch.
> 
> 
> 
> no, their code is buggy

For me v13 works on discordjs master but doesn't work using this library. Yes I am using it correctly.

**Comment by AngeloCore** [comment]
Thanks!
https://github.com/AngeloCore/discord-buttons/blob/dev/typings/index.d.ts#L219

**Pull request closed without merging**
