### PR TITLE
Removing stupid error ("ACTION_ROW" is not an int)

### PR DESCRIPTION
**Pull request by Micorksen**
Hello guys, i have getted an error "ACTION_ROW" is not an int.
I just create this pull-request to patch the problem.

Nothing to say here.
Good bye !

### CODE REVIEW

**Comment by AngeloCore** [comment]
just tell me when you get that error, i will fix

**Comment by AngeloCore** [comment]
Ok

**Comment by AngeloCore** [comment]
Inactive

**Comment by xHyroM** [comment]
> just tell me when you get that error, i will fix

slash cmd

**Pull request closed without merging**
