### PR TITLE
Rows

### PR DESCRIPTION
**Pull request by watchdogsrox**
Row Support: Based on PR of gaetan20 but it had some major bugs and a fatal flaw which searched for buttons in all messages even if they didnt have any buttons.

EXAMPLE: 2 Rows with 2 buttons in each.
` message.channel.send('hi', { buttons: [ [ button, button2 ], [ button3, button4 ] ] } );`

### CODE REVIEW

**Comment by gaetan20** [comment]
Can you suggest changes on my PR please ? It will be esasier for me to compare my errors

**Comment by watchdogsrox** [comment]
updated title

**Comment by watchdogsrox** [comment]
> Can you suggest changes on my PR please ? It will be esasier for me to compare my errors

done :) When using your fork, i couldn't send any messages because it kept checking for the buttons object in all messages, even those that didn't have anything to do with buttons. I included type handling so it works with single button objects, multiple buttons  (arrays) and rows of buttons (array of arrays).

**Comment by AngeloCore** [comment]
@watchdogsrox whats ur discord tag?

**Comment by watchdogsrox** [comment]
> @watchdogsrox whats ur discord tag?

We talked a bit last night, my tag is split#0420

**Pull request closed without merging**
