### PR TITLE
Support for v13 & v12 (bug fix for resolveString => verifyString)

### PR DESCRIPTION
**Pull request by milanmdev**
This PR fixes support for Discord.js v13. In a recent commit, Discord.js changed their `resolveString` function to `verifyString`.

This PR will add the ability for discord-buttons to check if the bot is on v13 or on v12, and choose which function it should use.

### CODE REVIEW

**Comment by AngeloCore** [comment]
You should check the [#dev](https://github.com/AngeloCore/discord-buttons/tree/dev) branch

**Comment by milanmdev** [comment]
@AngeloCore it's not in the dev branch?

**Comment by AngeloCore** [comment]
We merged today
https://github.com/AngeloCore/discord-buttons/blob/main/src/v12/Classes/MessageButton.js#L3

https://github.com/AngeloCore/discord-buttons/blob/main/src/v13/Classes/MessageButton.js#L3

**Comment by milanmdev** [comment]
Oh. Odd it still isn't working for me. Did it get published to NPM yet?

**Pull request closed without merging**
